name: Deploy to AWS Dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-west-1
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.9'
  ENVIRONMENT: dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install CDK dependencies
      run: npm ci
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/lambda_b/requirements.txt
        pip install pytest boto3
    
    - name: Run CDK tests (optional)
      run: npm test || true
    
    - name: CDK synth
      run: npm run synth
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      ENVIRONMENT: dev
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Destroy existing stack (cleanup)
      run: |
        # npm run destroy -- --force
        PIPELINE_NAME="entrix-energy-auction-pipeline-${ENVIRONMENT}"
        echo "Attempting to delete pipeline: $PIPELINE_NAME"
        aws codepipeline delete-pipeline --name $PIPELINE_NAME || echo "Pipeline not found"
        CODEBUILD_PROJECT="energy-auction-build-${ENVIRONMENT}"
        aws codebuild delete-project --name "$CODEBUILD_PROJECT"|| echo "CodeBuild project not found or already deleted"
        echo "Verifying deletion of CodeBuild project..."
        aws codebuild list-projects | grep "$CODEBUILD_PROJECT" || echo "✅ Project $CODEBUILD_PROJECT no longer exists"
      continue-on-error: true
    
    - name: Wait for cleanup
      run: sleep 60
    
    # GitHub PAT in Secrets Manager no longer needed - using GitHub Connections
    # The pipeline now uses CodeConnections for GitHub integration
    
    - name: Deploy to Dev
      run: npm run deploy -- --require-approval never
    
    - name: Notify deployment success
      if: success()
      run: |
        if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Deployment to Dev successful - ${{ github.sha }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }} || echo "Slack notification failed, but deployment succeeded"
        else
          echo "Slack webhook not configured, skipping notification"
        fi
    
    - name: Notify deployment failure
      if: failure()
      run: |
        if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ Deployment to Dev failed - ${{ github.sha }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }} || echo "Slack notification failed"
        else
          echo "Slack webhook not configured, skipping notification"
        fi
